general {
    hide_cursor = true
    disable_loading_bar = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    path = /home/guh/Pictures/wallpaper.jpg
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2

    inner_color = rgb(161c23)
    outer_color = rgb(79a8b0)

    font_color = rgb(e4dfe1)

    fade_on_empty = false

    placeholder_text = <i>Enter password...</i>

    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 64
    color = rgb(e4dfe1)

    position = 0, 80
    halign = center
    valign = center
}
